### ISSUE TITLE
Çoğul metinlerin kullanımı

### ISSUE THREAD

**Issue by guncebektas** [laravel-tr/Laravel5-lang#17]
Kimse yazmamış ama yaşadığım bir sorun ve sizlerde çoklu dil desteği olan sitelerde çoğul (plural) kelimeler için Laravel’in dökümanına uygun olarak dil değişkenlerinde

'Page' => 'Sayfa|Sayfalar',

şeklinde değişkenler tanımlamaya çalışmışsınızdır.

Lang::choice('_.Page', 2)

şeklinde bunları çağırmış ve sonunda da yahu “İngilizce’de çalışıyordu. Neden Türkçe’de çalışmıyor aynısını da yaptımdı ya lan!” demiş olabilirsiniz. 

Sorunun çözümü ise çok hoş olmasa da gayet basit;

\vendor\symfony\translation\PluralizationRules.php

dosyamızı açıyoruz.

case 'tr':

satırını bulunduğu yerden kesip case:’en’: satırının altına

case 'en':
case 'tr':

yapıştırıyoruz.

Kaynak: [http://guncebektas.com/laravelde-cogul-turkce-kelimelerin-kullanimi/](http://guncebektas.com/laravelde-cogul-turkce-kelimelerin-kullanimi/)

**Comment by sineld** [comment]
Vendor dizini içindeki dosyalarda değişiklik yapmak uygun değil, sonraki ilk update'de silinecektir.

Bu sebeple \vendor\symfony\translation\PluralizationRules.php dosyasını bir şekilde extend etmenin yolunu bulmalısınız.

**Comment by guncebektas** [comment]
Sorunun çözümü ise çok hoş olmasa da gayet basit, derken bunu kastetmiştim.
