### ISSUE TITLE
Laravel 5.8'de minimum şifre uzunluğu 8 oldu.

### ISSUE THREAD

**Issue by EmirCanSANCAR** [laravel-tr/Laravel5-lang#32]
bkz: laravel/framework#25957

passwords.php dosyası 8 karakter olarak güncellenmelidir. Eski minimum şifre uzunluğu 6 karakterdi.

**Comment by sineld** [comment]
Bu dil dosyası ile ilgili bir durum değil.

Auth/RegisterController içinde

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
        ]);
    }

bulunan kısımdan **min:6** kısmı **min:8** yapılmalıdır.

Konuyu kapatıyorum.

**Comment by hkan** [comment]
@sineld aslında Emir haklı. [passwords.php](https://github.com/laravel-tr/Laravel5-lang/blob/master/tr/passwords.php) dosyasında karakter sayısı sabit olarak yer alıyor. Orijinal repoda da aynı şekilde elle yazılmış, olduğu gibi çevirmişiz. Tekrar açıyorum o yüzden.

**Comment by sineld** [comment]
Düzeltilmiş halini gönderebilirsin Hakan.
