### ISSUE TITLE
Laravel sürümleri

### ISSUE THREAD

**Issue by angelside** [laravel-tr/Laravel5-lang#6]
Güncelleye güncelleye dosyaları 5.2.* seviyesine getirdik ancak şu anki güncel sürüm, 5.1 LTS ile uyumlu mu değil mi emin değilim. Bir ihtimal, eğer gerekli görülürse 5.1 ve 5.2 dil dosyaları farklı branch olarak ayrılabilir.

**Comment by sineld** [comment]
Yapıldı.
